apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: nginx
    env: main
spec:
  replicas: 2  # Number of instances (pods) to run
  selector:
    matchLabels:
      app: nginx
# everything under template is the definition of the pod that will be created.      
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: web-app
        image: dockercontainer-main/main:latest
        ports:
        - containerPort: 80
